version: '3.8'

services:
  iris-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../logs:/app/logs
      - ../models:/app/models
      - ../data:/app/data
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mlflow:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    volumes:
      - ../mlruns:/mlruns
    working_dir: /app
    command: >
      sh -c "pip install mlflow &&
             mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri file:///mlruns"
    restart: unless-stopped

networks:
  default:
    name: iris-mlops-network
